package com.lanou.entity;
// Generated 2017-12-5 11:04:30 by Hibernate Tools 4.3.5.Final

import java.math.BigDecimal;
import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * BizClaimVouyearStatistics generated by hbm2java
 */
@Entity
@Table(name = "biz_claim_vouyear__statistics", catalog = "oa")
public class BizClaimVouyearStatistics implements java.io.Serializable {

	private Integer id;
	private SysDepartment sysDepartment;
	private BigDecimal totalCount;
	private int year;
	private Date modifyTime;

	public BizClaimVouyearStatistics() {
	}

	public BizClaimVouyearStatistics(SysDepartment sysDepartment, BigDecimal totalCount, int year) {
		this.sysDepartment = sysDepartment;
		this.totalCount = totalCount;
		this.year = year;
	}

	public BizClaimVouyearStatistics(SysDepartment sysDepartment, BigDecimal totalCount, int year, Date modifyTime) {
		this.sysDepartment = sysDepartment;
		this.totalCount = totalCount;
		this.year = year;
		this.modifyTime = modifyTime;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)

	@Column(name = "ID", unique = true, nullable = false)
	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "DEPARTMENT_ID", nullable = false)
	public SysDepartment getSysDepartment() {
		return this.sysDepartment;
	}

	public void setSysDepartment(SysDepartment sysDepartment) {
		this.sysDepartment = sysDepartment;
	}

	@Column(name = "TOTAL_COUNT", nullable = false, precision = 30)
	public BigDecimal getTotalCount() {
		return this.totalCount;
	}

	public void setTotalCount(BigDecimal totalCount) {
		this.totalCount = totalCount;
	}

	@Column(name = "YEAR", nullable = false)
	public int getYear() {
		return this.year;
	}

	public void setYear(int year) {
		this.year = year;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "MODIFY_TIME", length = 19)
	public Date getModifyTime() {
		return this.modifyTime;
	}

	public void setModifyTime(Date modifyTime) {
		this.modifyTime = modifyTime;
	}

}
