package com.lanou.entity;
// Generated 2017-12-5 11:04:30 by Hibernate Tools 4.3.5.Final

import java.math.BigDecimal;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;

/**
 * BizClaimVoucherDetail generated by hbm2java
 */
@Entity
@Table(name = "biz_claim_voucher_detail", catalog = "oa")
public class BizClaimVoucherDetail implements java.io.Serializable {

	private Integer id;
	private BizClaimVoucher bizClaimVoucher;
	private String item;
	private BigDecimal account;
	private String des;

	public BizClaimVoucherDetail() {
	}

	public BizClaimVoucherDetail(BizClaimVoucher bizClaimVoucher, String item, BigDecimal account, String des) {
		this.bizClaimVoucher = bizClaimVoucher;
		this.item = item;
		this.account = account;
		this.des = des;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)

	@Column(name = "ID", unique = true, nullable = false)
	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "MAIN_ID", nullable = false)
	public BizClaimVoucher getBizClaimVoucher() {
		return this.bizClaimVoucher;
	}

	public void setBizClaimVoucher(BizClaimVoucher bizClaimVoucher) {
		this.bizClaimVoucher = bizClaimVoucher;
	}

	@Column(name = "ITEM", nullable = false, length = 20)
	public String getItem() {
		return this.item;
	}

	public void setItem(String item) {
		this.item = item;
	}

	@Column(name = "ACCOUNT", nullable = false, precision = 20)
	public BigDecimal getAccount() {
		return this.account;
	}

	public void setAccount(BigDecimal account) {
		this.account = account;
	}

	@Column(name = "DES", nullable = false, length = 200)
	public String getDes() {
		return this.des;
	}

	public void setDes(String des) {
		this.des = des;
	}

}
