package com.lanou.entity;
// Generated 2017-12-5 11:04:30 by Hibernate Tools 4.3.5.Final

import java.math.BigDecimal;
import java.util.Date;
import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * BizClaimVoucher generated by hbm2java
 */
@Entity
@Table(name = "biz_claim_voucher", catalog = "oa")
public class BizClaimVoucher implements java.io.Serializable {

	private Integer id;
	private SysEmployee sysEmployeeByCreateSn;
	private SysEmployee sysEmployeeByNextDealSn;
	private Date createTime;
	private String event;
	private BigDecimal totalAccount;
	private String status;
	private Date modifyTime;
	private Set<BizCheckResult> bizCheckResults = new HashSet<BizCheckResult>(0);
	private Set<BizClaimVoucherDetail> bizClaimVoucherDetails = new HashSet<BizClaimVoucherDetail>(0);

	public BizClaimVoucher() {
	}

	public BizClaimVoucher(SysEmployee sysEmployeeByCreateSn, String event, BigDecimal totalAccount, String status) {
		this.sysEmployeeByCreateSn = sysEmployeeByCreateSn;
		this.event = event;
		this.totalAccount = totalAccount;
		this.status = status;
	}

	public BizClaimVoucher(SysEmployee sysEmployeeByCreateSn, SysEmployee sysEmployeeByNextDealSn, Date createTime,
			String event, BigDecimal totalAccount, String status, Date modifyTime, Set<BizCheckResult> bizCheckResults,
			Set<BizClaimVoucherDetail> bizClaimVoucherDetails) {
		this.sysEmployeeByCreateSn = sysEmployeeByCreateSn;
		this.sysEmployeeByNextDealSn = sysEmployeeByNextDealSn;
		this.createTime = createTime;
		this.event = event;
		this.totalAccount = totalAccount;
		this.status = status;
		this.modifyTime = modifyTime;
		this.bizCheckResults = bizCheckResults;
		this.bizClaimVoucherDetails = bizClaimVoucherDetails;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)

	@Column(name = "ID", unique = true, nullable = false)
	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "CREATE_SN", nullable = false)
	public SysEmployee getSysEmployeeByCreateSn() {
		return this.sysEmployeeByCreateSn;
	}

	public void setSysEmployeeByCreateSn(SysEmployee sysEmployeeByCreateSn) {
		this.sysEmployeeByCreateSn = sysEmployeeByCreateSn;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "NEXT_DEAL_SN")
	public SysEmployee getSysEmployeeByNextDealSn() {
		return this.sysEmployeeByNextDealSn;
	}

	public void setSysEmployeeByNextDealSn(SysEmployee sysEmployeeByNextDealSn) {
		this.sysEmployeeByNextDealSn = sysEmployeeByNextDealSn;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "CREATE_TIME", length = 19)
	public Date getCreateTime() {
		return this.createTime;
	}

	public void setCreateTime(Date createTime) {
		this.createTime = createTime;
	}

	@Column(name = "EVENT", nullable = false)
	public String getEvent() {
		return this.event;
	}

	public void setEvent(String event) {
		this.event = event;
	}

	@Column(name = "TOTAL_ACCOUNT", nullable = false, precision = 10)
	public BigDecimal getTotalAccount() {
		return this.totalAccount;
	}

	public void setTotalAccount(BigDecimal totalAccount) {
		this.totalAccount = totalAccount;
	}

	@Column(name = "STATUS", nullable = false, length = 20)
	public String getStatus() {
		return this.status;
	}

	public void setStatus(String status) {
		this.status = status;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "MODIFY_TIME", length = 19)
	public Date getModifyTime() {
		return this.modifyTime;
	}

	public void setModifyTime(Date modifyTime) {
		this.modifyTime = modifyTime;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "bizClaimVoucher")
	public Set<BizCheckResult> getBizCheckResults() {
		return this.bizCheckResults;
	}

	public void setBizCheckResults(Set<BizCheckResult> bizCheckResults) {
		this.bizCheckResults = bizCheckResults;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "bizClaimVoucher")
	public Set<BizClaimVoucherDetail> getBizClaimVoucherDetails() {
		return this.bizClaimVoucherDetails;
	}

	public void setBizClaimVoucherDetails(Set<BizClaimVoucherDetail> bizClaimVoucherDetails) {
		this.bizClaimVoucherDetails = bizClaimVoucherDetails;
	}

}
