package com.lanou.entity;
// Generated 2017-12-5 11:04:30 by Hibernate Tools 4.3.5.Final

import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * SysDepartment generated by hbm2java
 */
@Entity
@Table(name = "sys_department", catalog = "oa")
public class SysDepartment implements java.io.Serializable {

	private Integer id;
	private String name;
	private Set<BizClaimVouyearStatistics> bizClaimVouyearStatisticses = new HashSet<BizClaimVouyearStatistics>(0);
	private Set<BizClaimVoucherStatistics> bizClaimVoucherStatisticses = new HashSet<BizClaimVoucherStatistics>(0);
	private Set<SysEmployee> sysEmployees = new HashSet<SysEmployee>(0);

	public SysDepartment() {
	}

	public SysDepartment(String name) {
		this.name = name;
	}

	public SysDepartment(String name, Set<BizClaimVouyearStatistics> bizClaimVouyearStatisticses,
			Set<BizClaimVoucherStatistics> bizClaimVoucherStatisticses, Set<SysEmployee> sysEmployees) {
		this.name = name;
		this.bizClaimVouyearStatisticses = bizClaimVouyearStatisticses;
		this.bizClaimVoucherStatisticses = bizClaimVoucherStatisticses;
		this.sysEmployees = sysEmployees;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)

	@Column(name = "ID", unique = true, nullable = false)
	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	@Column(name = "NAME", nullable = false, length = 50)
	public String getName() {
		return this.name;
	}

	public void setName(String name) {
		this.name = name;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "sysDepartment")
	public Set<BizClaimVouyearStatistics> getBizClaimVouyearStatisticses() {
		return this.bizClaimVouyearStatisticses;
	}

	public void setBizClaimVouyearStatisticses(Set<BizClaimVouyearStatistics> bizClaimVouyearStatisticses) {
		this.bizClaimVouyearStatisticses = bizClaimVouyearStatisticses;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "sysDepartment")
	public Set<BizClaimVoucherStatistics> getBizClaimVoucherStatisticses() {
		return this.bizClaimVoucherStatisticses;
	}

	public void setBizClaimVoucherStatisticses(Set<BizClaimVoucherStatistics> bizClaimVoucherStatisticses) {
		this.bizClaimVoucherStatisticses = bizClaimVoucherStatisticses;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "sysDepartment")
	public Set<SysEmployee> getSysEmployees() {
		return this.sysEmployees;
	}

	public void setSysEmployees(Set<SysEmployee> sysEmployees) {
		this.sysEmployees = sysEmployees;
	}

}
