package com.lanou.entity;
// Generated 2017-12-5 11:04:30 by Hibernate Tools 4.3.5.Final

import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * SysEmployee generated by hbm2java
 */
@Entity
@Table(name = "sys_employee", catalog = "oa")
public class SysEmployee implements java.io.Serializable {

	private Integer sn;
	private SysDepartment sysDepartment;
	private SysPosition sysPosition;
	private String name;
	private String password;
	private String status;
	private Set<BizClaimVoucher> bizClaimVouchersForCreateSn = new HashSet<BizClaimVoucher>(0);
	private Set<BizClaimVoucher> bizClaimVouchersForNextDealSn = new HashSet<BizClaimVoucher>(0);
	private Set<BizCheckResult> bizCheckResults = new HashSet<BizCheckResult>(0);
	private Set<BizLeave> bizLeaves = new HashSet<BizLeave>(0);

	public SysEmployee() {
	}

	public SysEmployee(SysDepartment sysDepartment, SysPosition sysPosition, String name, String password,
			String status) {
		this.sysDepartment = sysDepartment;
		this.sysPosition = sysPosition;
		this.name = name;
		this.password = password;
		this.status = status;
	}

	public SysEmployee(SysDepartment sysDepartment, SysPosition sysPosition, String name, String password,
			String status, Set<BizClaimVoucher> bizClaimVouchersForCreateSn,
			Set<BizClaimVoucher> bizClaimVouchersForNextDealSn, Set<BizCheckResult> bizCheckResults,
			Set<BizLeave> bizLeaves) {
		this.sysDepartment = sysDepartment;
		this.sysPosition = sysPosition;
		this.name = name;
		this.password = password;
		this.status = status;
		this.bizClaimVouchersForCreateSn = bizClaimVouchersForCreateSn;
		this.bizClaimVouchersForNextDealSn = bizClaimVouchersForNextDealSn;
		this.bizCheckResults = bizCheckResults;
		this.bizLeaves = bizLeaves;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)

	@Column(name = "SN", unique = true, nullable = false)
	public Integer getSn() {
		return this.sn;
	}

	public void setSn(Integer sn) {
		this.sn = sn;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "DEPARTMENT_ID", nullable = false)
	public SysDepartment getSysDepartment() {
		return this.sysDepartment;
	}

	public void setSysDepartment(SysDepartment sysDepartment) {
		this.sysDepartment = sysDepartment;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "POSITION_ID", nullable = false)
	public SysPosition getSysPosition() {
		return this.sysPosition;
	}

	public void setSysPosition(SysPosition sysPosition) {
		this.sysPosition = sysPosition;
	}

	@Column(name = "NAME", nullable = false, length = 50)
	public String getName() {
		return this.name;
	}

	public void setName(String name) {
		this.name = name;
	}

	@Column(name = "PASSWORD", nullable = false, length = 50)
	public String getPassword() {
		return this.password;
	}

	public void setPassword(String password) {
		this.password = password;
	}

	@Column(name = "STATUS", nullable = false, length = 20)
	public String getStatus() {
		return this.status;
	}

	public void setStatus(String status) {
		this.status = status;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "sysEmployeeByCreateSn")
	public Set<BizClaimVoucher> getBizClaimVouchersForCreateSn() {
		return this.bizClaimVouchersForCreateSn;
	}

	public void setBizClaimVouchersForCreateSn(Set<BizClaimVoucher> bizClaimVouchersForCreateSn) {
		this.bizClaimVouchersForCreateSn = bizClaimVouchersForCreateSn;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "sysEmployeeByNextDealSn")
	public Set<BizClaimVoucher> getBizClaimVouchersForNextDealSn() {
		return this.bizClaimVouchersForNextDealSn;
	}

	public void setBizClaimVouchersForNextDealSn(Set<BizClaimVoucher> bizClaimVouchersForNextDealSn) {
		this.bizClaimVouchersForNextDealSn = bizClaimVouchersForNextDealSn;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "sysEmployee")
	public Set<BizCheckResult> getBizCheckResults() {
		return this.bizCheckResults;
	}

	public void setBizCheckResults(Set<BizCheckResult> bizCheckResults) {
		this.bizCheckResults = bizCheckResults;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "sysEmployee")
	public Set<BizLeave> getBizLeaves() {
		return this.bizLeaves;
	}

	public void setBizLeaves(Set<BizLeave> bizLeaves) {
		this.bizLeaves = bizLeaves;
	}

}
