package com.lanou.entity;
// Generated 2017-12-5 11:04:30 by Hibernate Tools 4.3.5.Final

import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * SysPosition generated by hbm2java
 */
@Entity
@Table(name = "sys_position", catalog = "oa")
public class SysPosition implements java.io.Serializable {

	private Integer id;
	private String nameCn;
	private String nameEn;
	private Set<SysEmployee> sysEmployees = new HashSet<SysEmployee>(0);

	public SysPosition() {
	}

	public SysPosition(String nameCn, String nameEn) {
		this.nameCn = nameCn;
		this.nameEn = nameEn;
	}

	public SysPosition(String nameCn, String nameEn, Set<SysEmployee> sysEmployees) {
		this.nameCn = nameCn;
		this.nameEn = nameEn;
		this.sysEmployees = sysEmployees;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)

	@Column(name = "ID", unique = true, nullable = false)
	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	@Column(name = "NAME_CN", nullable = false, length = 50)
	public String getNameCn() {
		return this.nameCn;
	}

	public void setNameCn(String nameCn) {
		this.nameCn = nameCn;
	}

	@Column(name = "NAME_EN", nullable = false, length = 50)
	public String getNameEn() {
		return this.nameEn;
	}

	public void setNameEn(String nameEn) {
		this.nameEn = nameEn;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "sysPosition")
	public Set<SysEmployee> getSysEmployees() {
		return this.sysEmployees;
	}

	public void setSysEmployees(Set<SysEmployee> sysEmployees) {
		this.sysEmployees = sysEmployees;
	}

}
